version: '3.8'

services:
  fastapi:
    build:
      context: ..
      dockerfile: docker/fastapi.Dockerfile
    ports:
      - "8000:8000"

  mlflow:
    build:
      context: ..
      dockerfile: docker/mlflow.Dockerfile
    ports:
      - "5000:5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - fastapi
      - mlflow
