name: Deploy API and MLflow

on:
  workflow_run:
    workflows: ["ML Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t my-fastapi-mlflow .

      - name: Run container with Ngrok
        env:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        run: |
          docker run -d -e NGROK_AUTH_TOKEN=$NGROK_AUTH_TOKEN -p 8000:8000 -p 5000:5000 my-fastapi-mlflow
