name: Deploy Pipeline

on:
  workflow_run:
    workflows: ["ML Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download mlruns from previous workflow
      uses: actions/download-artifact@v4
      with:
        name: mlruns
        path: mlruns/

    - name: Download outputs from previous workflow
      uses: actions/download-artifact@v4
      with:
        name: outputs
        path: outputs/

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build and run containers
      run: docker-compose up -d --build

    - name: Download and set up Ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin
        ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start Ngrok tunnels
      run: |
        nohup ngrok http 8000 > ngrok_fastapi.log &
        nohup ngrok http 5000 > ngrok_mlflow.log &
        sleep 10

    - name: Show public URLs
      run: |
        curl http://localhost:4040/api/tunnels > tunnels.json
        echo "Public URLs:"
        cat tunnels.json | jq -r '.tunnels[] | .name + ": " + .public_url'
        sleep 100
